/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AssignmentMainClasses;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author luke2720
 */
public class TestFace extends javax.swing.JFrame {

    /**
     * Creates new form TestFace
     */
    Face f;
    public TestFace() {
        initComponents();
        f = new Face(facepanel.getGraphics(),150,75);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facepanel = new javax.swing.JPanel();
        movebtn = new javax.swing.JButton();
        resizebtn = new javax.swing.JButton();
        colorbtn = new javax.swing.JButton();
        moodbtn = new javax.swing.JButton();
        initfacebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        facepanel.setBackground(new java.awt.Color(255, 255, 255));
        facepanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout facepanelLayout = new javax.swing.GroupLayout(facepanel);
        facepanel.setLayout(facepanelLayout);
        facepanelLayout.setHorizontalGroup(
            facepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        facepanelLayout.setVerticalGroup(
            facepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        movebtn.setText("MOVE FACE");
        movebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movebtnActionPerformed(evt);
            }
        });

        resizebtn.setText("RESIZE FACE");
        resizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizebtnActionPerformed(evt);
            }
        });

        colorbtn.setText("CHANGE COLOUR");
        colorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorbtnActionPerformed(evt);
            }
        });

        moodbtn.setText("TOGGLE MOOD");
        moodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodbtnActionPerformed(evt);
            }
        });

        initfacebtn.setText("SET INITIAL FACE");
        initfacebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initfacebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resizebtn)
                        .addGap(18, 18, 18)
                        .addComponent(colorbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moodbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(initfacebtn)
                        .addGap(179, 179, 179))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(facepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movebtn)
                    .addComponent(resizebtn)
                    .addComponent(colorbtn)
                    .addComponent(moodbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(facepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(initfacebtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initfacebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initfacebtnActionPerformed
        f.erase();
        f = new Face(facepanel.getGraphics(),150,75);
        f.draw();
    }//GEN-LAST:event_initfacebtnActionPerformed

    private void movebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movebtnActionPerformed
        int newx = Integer.parseInt(JOptionPane.showInputDialog(this,"Enter new X: "));
        int newy = Integer.parseInt(JOptionPane.showInputDialog(this,"Enter new Y: "));
        f.setLoc(newx,newy);
    }//GEN-LAST:event_movebtnActionPerformed

    private void moodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodbtnActionPerformed
        f.mood();
    }//GEN-LAST:event_moodbtnActionPerformed

    private void colorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorbtnActionPerformed
        Color newc = JColorChooser.showDialog(this, "Pick new face color.",Color.red);
        Color newec = JColorChooser.showDialog(this, "Pick new eye color.",Color.yellow);
        f.setColour(newc,newec);
    }//GEN-LAST:event_colorbtnActionPerformed

    private void resizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizebtnActionPerformed
        int newd = Integer.parseInt(JOptionPane.showInputDialog(this,"Enter new diameter: "));
        f.resize(newd);
    }//GEN-LAST:event_resizebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorbtn;
    private javax.swing.JPanel facepanel;
    private javax.swing.JButton initfacebtn;
    private javax.swing.JButton moodbtn;
    private javax.swing.JButton movebtn;
    private javax.swing.JButton resizebtn;
    // End of variables declaration//GEN-END:variables
}
